const ActionTypes = {
    SAVE_GROUPS: 'SAVE_GROUPS',
    SIGN_IN_REQUESTED: 'SIGN_IN_REQUESTED',
    SIGN_IN_SUCCESSED: 'SIGN_IN_SUCCESSED',
    SIGN_IN_FAILED: 'SIGN_IN_FAILED',
    LOGOUT: 'LOGOUT',
    SHOW_ALERT: 'SHOW_ALERT',
    HIDE_ALERT: 'HIDE_ALERT',
    CREATE_USER_REQUEST_STARTED: 'CREATE_USER_REQUEST_STARTED',
    CREATE_USER_REQUEST_SUCCEEDED: 'CREATE_USER_REQUEST_SUCCEEDED',
    CREATE_USER_REQUEST_FAILED: 'CREATE_USER_REQUEST_FAILED',
    RESET_CREATE_USER_REQUEST_STATE: 'RESET_CREATE_USER_REQUEST_STATE',
    GET_USERS_REQUEST_STARTED: 'GET_USERS_REQUEST_STARTED',
    GET_USERS_REQUEST_SUCCEEDED: 'GET_USERS_REQUEST_SUCCEEDED',
    GET_USERS_REQUEST_FAILED: 'GET_USERS_REQUEST_FAILED',
    UPLOAD_FILE_REQUEST_STARTED: 'UPLOAD_FILE_REQUEST_STARTED',
    UPLOAD_FILE_REQUEST_SUCCEEDED: 'UPLOAD_FILE_REQUEST_SUCCEEDED',
    UPLOAD_FILE_REQUEST_FAILED: 'UPLOAD_FILE_REQUEST_FAILED',
    GET_MEDIA_REQUEST_STARTED: 'GET_MEDIA_REQUEST_STARTED',
    GET_MEDIA_REQUEST_SUCCEEDED: 'GET_MEDIA_REQUEST_SUCCEEDED',
    GET_MEDIA_REQUEST_FAILED: 'GET_MEDIA_REQUEST_FAILED',
    GET_ALL_MEDIA_REQUEST_STARTED: 'GET_ALL_MEDIA_REQUEST_STARTED',
    GET_ALL_MEDIA_REQUEST_SUCCEEDED: 'GET_ALL_MEDIA_REQUEST_SUCCEEDED',
    GET_ALL_MEDIA_REQUEST_FAILED: 'GET_ALL_MEDIA_REQUEST_FAILED',
    UPDATE_MEDIA_REQUEST_STARTED: 'UPDATE_MEDIA_REQUEST_STARTED',
    UPDATE_MEDIA_REQUEST_SUCCEEDED: 'UPDATE_MEDIA_REQUEST_SUCCEEDED',
    UPDATE_MEDIA_REQUEST_FAILED: 'UPDATE_MEDIA_REQUEST_FAILED',

    //CREATE GIFT CATEGORY ACTION TYPES
    CREATE_GIFT_CATEGORY_REQUEST: 'CREATE_GIFT_CATEGORY_REQUEST',
    CREATE_GIFT_CATEGORY_SUCCESS: 'CREATE_GIFT_CATEGORY_SUCCESS',
    CREATE_GIFT_CATEGORY_FAIL: 'CREATE_GIFT_CATEGORY_FAIL',

    //UPDATE GIFT CATEGORY ACTION TYPES
    UPDATE_GIFT_CATEGORY_REQUEST: 'UPDATE_GIFT_CATEGORY_REQUEST',
    UPDATE_GIFT_CATEGORY_SUCCESS: 'UPDATE_GIFT_CATEGORY_SUCCESS',
    UPDATE_GIFT_CATEGORY_FAIL: 'UPDATE_GIFT_CATEGORY_FAIL',

    //DELETE GIFT CATEGORY ACTION TYPES
    DELETE_GIFT_CATEGORY_REQUEST: 'DELETE_GIFT_CATEGORY_REQUEST',
    DELETE_GIFT_CATEGORY_SUCCESS: 'DELETE_GIFT_CATEGORY_SUCCESS',
    DELETE_GIFT_CATEGORY_FAIL: 'DELETE_GIFT_CATEGORY_FAIL',

    //GETALL GIFT CATEGORIES ACTION TYPES
    GETALL_GIFT_CATEGORY_REQUEST: 'GETALL_GIFT_CATEGORY_REQUEST',
    GETALL_GIFT_CATEGORY_SUCCESS: 'GETALL_GIFT_CATEGORY_SUCCESS',
    GETALL_GIFT_CATEGORY_FAIL: 'GETALL_GIFT_CATEGORY_FAIL',

    //ADD GIFT ACTION TYPES
    ADD_GIFT_REQUEST: 'ADD_GIFT_REQUEST',
    ADD_GIFT_SUCCESS: 'ADD_GIFT_SUCCESS',
    ADD_GIFT_FAIL: 'ADD_GIFT_FAIL',

    //UPDATE ADD GIFT ACTION TYPES
    UPDATE_GIFT_REQUEST: 'UPDATE_GIFT_REQUEST',
    UPDATE_GIFT_SUCCESS: 'UPDATE_GIFT_SUCCESS',
    UPDATE_GIFT_FAIL: 'UPDATE_GIFT_FAIL',

    //DELETE ADD GIFT ACTION TYPES
    DELETE_GIFT_REQUEST: 'DELETE_GIFT_REQUEST',
    DELETE_GIFT_SUCCESS: 'DELETE_GIFT_SUCCESS',
    DELETE_GIFT_FAIL: 'DELETE_GIFT_FAIL',

    //GETALL GIFTS ACTION TYPES
    GETALL_GIFT_REQUEST: 'GETALL_GIFT_REQUEST',
    GETALL_GIFT_SUCCESS: 'GETALL_GIFT_SUCCESS',
    GETALL_GIFT_FAIL: 'GETALL_GIFT_FAIL',

}

export default ActionTypes;