export const GOTTEMPLATE = "GOTTEMPLATE";
export const GOTVIDEOTEMPLATE = "GOTVIDEOTEMPLATE";
const ActionTypes = {
    SAVE_GROUPS: 'SAVE_GROUPS',
    SIGN_IN_REQUESTED: 'SIGN_IN_REQUESTED',
    SIGN_IN_SUCCESSED: 'SIGN_IN_SUCCESSED',
    SIGN_IN_FAILED: 'SIGN_IN_FAILED',
    LOGOUT: 'LOGOUT',
    SHOW_ALERT: 'SHOW_ALERT',
    HIDE_ALERT: 'HIDE_ALERT',
    CREATE_USER_REQUEST_STARTED: 'CREATE_USER_REQUEST_STARTED',
    CREATE_USER_REQUEST_SUCCEEDED: 'CREATE_USER_REQUEST_SUCCEEDED',
    CREATE_USER_REQUEST_FAILED: 'CREATE_USER_REQUEST_FAILED',
    RESET_CREATE_USER_REQUEST_STATE: 'RESET_CREATE_USER_REQUEST_STATE',
    GET_USERS_REQUEST_STARTED: 'GET_USERS_REQUEST_STARTED',
    GET_USERS_REQUEST_SUCCEEDED: 'GET_USERS_REQUEST_SUCCEEDED',
    GET_USERS_REQUEST_FAILED: 'GET_USERS_REQUEST_FAILED',
    UPLOAD_FILE_REQUEST_STARTED: 'UPLOAD_FILE_REQUEST_STARTED',
    UPLOAD_FILE_REQUEST_SUCCEEDED: 'UPLOAD_FILE_REQUEST_SUCCEEDED',
    UPLOAD_FILE_REQUEST_FAILED: 'UPLOAD_FILE_REQUEST_FAILED',
    GET_MEDIA_REQUEST_STARTED: 'GET_MEDIA_REQUEST_STARTED',
    GET_MEDIA_REQUEST_SUCCEEDED: 'GET_MEDIA_REQUEST_SUCCEEDED',
    GET_MEDIA_REQUEST_FAILED: 'GET_MEDIA_REQUEST_FAILED',
    GET_ALL_MEDIA_REQUEST_STARTED: 'GET_ALL_MEDIA_REQUEST_STARTED',
    GET_ALL_MEDIA_REQUEST_SUCCEEDED: 'GET_ALL_MEDIA_REQUEST_SUCCEEDED',
    GET_ALL_MEDIA_REQUEST_FAILED: 'GET_ALL_MEDIA_REQUEST_FAILED',
    UPDATE_MEDIA_REQUEST_STARTED: 'UPDATE_MEDIA_REQUEST_STARTED',
    UPDATE_MEDIA_REQUEST_SUCCEEDED: 'UPDATE_MEDIA_REQUEST_SUCCEEDED',
    UPDATE_MEDIA_REQUEST_FAILED: 'UPDATE_MEDIA_REQUEST_FAILED',
}

export default ActionTypes;